source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jemoji"
  gem "classifier-reborn"
  gem 'jekyll-feed'
end

gem "webrick", "~> 1.7"
